services:
  gateway:
    build:
      context: ./rinha-gateway
      dockerfile: Dockerfile
    hostname: gateway
    container_name: rinha-gateway
    environment:
      - API_SOCKETS=/sockets/go.sock.1,/sockets/go.sock.2
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - sockets:/sockets
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '50MB'

  api1: &api
    build:
      context: ./rinha-api
      dockerfile: Dockerfile
    hostname: api1
    container_name: rinha-api01
    environment:
      - SERVER_SOCKET=/sockets/go.sock.1
      - STORAGE_SOCKET=/sockets/storage.sock
    volumes:
      - sockets:/sockets
    depends_on:
      - storage
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '100MB'

  api2:
    <<: *api
    hostname: api1
    container_name: rinha-api02
    environment:
      - SERVER_SOCKET=/sockets/go.sock.2
      - STORAGE_SOCKET=/sockets/storage.sock

  storage:
    build:
      context: ./rinha-storage
      dockerfile: Dockerfile
    hostname: storage
    container_name: rinha-storage
    environment:
      - STORAGE_SOCKET=/sockets/storage.sock
    volumes:
      - sockets:/sockets
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100MB'

  # SOON!
  # prometheus:
  #   image: prom/prometheus:v2.54.1
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus:/prometheus
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - backend

volumes:
  sockets:

networks:
  backend:
  payment-processor:
    external: true
