name: rinha-2025

x-api_template: &api_template
  image: macedot/rinha-2025:latest
  env_file:
    - .env
  depends_on:
    - redis
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.60"
        memory: "100MB"

services:
  api01:
    <<: *api_template
    hostname: api01

  api02:
    <<: *api_template
    hostname: api02

  gateway:
    image: haproxy:3.2.3-alpine
    hostname: rinha-gateway
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api01
      - api02
    networks:
      - backend
    ports:
      - "9999:8080"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "75MB"

  redis:
    image: redis:8-alpine
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "75MB"

networks:
  backend:
  payment-processor:
    external: true
